vel:
  type: "iai_robot_mechanism_controllers/MultiJointVelocityImpedanceController"
  joints:
    - x_joint
    - y_joint
    - angle_joint
    - shoulder_pan_joint
    - shoulder_lift_joint
    - elbow_joint
    - wrist_1_joint
    - wrist_2_joint
    - wrist_3_joint
  gains:
    x_joint: &pid_gains
      p: 2.5
      i: 0.0
      d: 0.0
    y_joint: *pid_gains
    angle_joint: *pid_gains
    shoulder_pan_joint: *pid_gains
    shoulder_lift_joint: *pid_gains
    elbow_joint: *pid_gains
    wrist_1_joint: *pid_gains
    wrist_2_joint: *pid_gains
    wrist_3_joint: *pid_gains