state_separator:
  joint_names:
    - human_x_joint
    - human_y_joint
    - human_angle_joint
    - human_upper_arm_joint
    - human_lower_arm_joint
    - human_hand_joint
pos_controller: &controller_params
  vel_command_type: MultiJointVelocityImpedanceCommand
  max_speed: 1.9
  p_gain: 10
  stiffness: 200