vel:
  type: "iai_robot_mechanism_controllers/MultiJointVelocityImpedanceController"
  joints:
    - human_x_joint
    - human_y_joint
    - human_angle_joint
    - human_upper_arm_joint
    - human_lower_arm_joint
    - human_hand_joint
  gains:
    human_x_joint: &pid_gains
      p: 2.5
      i: 0.0
      d: 0.0
    human_y_joint: *pid_gains
    human_angle_joint: *pid_gains
    human_upper_arm_joint: *pid_gains
    human_lower_arm_joint: *pid_gains
    human_hand_joint: *pid_gains