<?xml version="1.0"?>  
<robot name="mobile_manipulator" xmlns:xacro="http://ros.org/wiki/xacro">  
  <include filename="$(find agv_description)/urdf/agv.xacro"/>
  <include filename="$(find ur_robot)/urdf/ur5.urdf.xacro"/>    
  <include filename="$(find mm_rviz_sim)/urdf/rg2.xacro"/>
  <include filename="$(find mm_rviz_sim)/urdf/force_sensor.xacro"/> 
  <xacro:ur5_robot prefix="" joint_limited="true"/>

  <!--ur5_support-->
  <xacro:property name="ur5_support_height" value="0.01"/>
  <joint name="ur5_2_agv" type="fixed">
    <parent link="agv_base_link" />
    <child link="base_link" />
    <origin xyz="0.1395 0 ${ur5_support_height + 0.393}" rpy="0.0 0.0 0.0" />
  </joint>
  
  <link name="ur5_support">
    <visual>
     <origin xyz="0 0 ${ur5_support_height/2}" rpy="0 0 0"/>
      <material name="grey">
        <color rgba="${185/255} ${185/255} ${185/255} 1.0"/>
      </material>
     <geometry>
       <cylinder radius="0.075" length="${ur5_support_height}"/>
     </geometry>
    </visual>
    <collision>
     <origin xyz="0 0 ${ur5_support_height/2}" rpy="0 0 0"/>
     <geometry>
       <cylinder radius="0.08" length="${ur5_support_height}"/>
     </geometry>
    </collision>
  </link>

  <joint name="ur5_support_2_agv" type="fixed">
    <parent link="base_link" />
    <child link="ur5_support" />
    <origin xyz="0 0 -${ur5_support_height}" rpy="0.0 0.0 0.0" />
  </joint>

</robot>
